### ISSUE TITLE
Failed to load the atom-discord package

### ISSUE THREAD

**Issue by ghost** [HelloWorld017/atom-discord#109]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04.1
**Thrown From**: [atom-discord](https://github.com/HelloWorld017/atom-discord) package 2.0.2

### Stack Trace

Failed to load the atom-discord package

```
At Cannot find module '../i18n/index.json'
Require stack:
- /home/mad/.atom/packages/atom-discord/src/config.js
- /home/mad/.atom/packages/atom-discord/src/index.js
- /usr/share/atom/resources/app.asar/static/index.html

Error: Cannot find module '../i18n/index.json'
Require stack:
- /home/mad/.atom/packages/atom-discord/src/config.js
- /home/mad/.atom/packages/atom-discord/src/index.js
- /usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/atom-discord/src/config.js:1:173)
    at /packages/atom-discord/src/config.js:443:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/atom-discord/src/index.js:1:177)
    at /packages/atom-discord/src/index.js:336:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695413)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3193818)
    at /usr/share/atom/resources/app/static/<embedded>:11:3180358
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3179190)
    at Package.load (/usr/share/atom/resources/app/static/<embedded>:11:3179931)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/static/<embedded>:11:381611)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/static/<embedded>:11:380339)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382911)
    at /usr/share/atom/resources/app/static/<embedded>:11:915622
    at r (/usr/share/atom/resources/app/static/<embedded>:11:910228)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1089018)
    at /usr/share/atom/resources/app/static/<embedded>:14:1089172
    at Socket.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:1087774)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
     -6:32 core:confirm (input.hidden-input)
     -6:32 application:show-preferences (div.tool-panel.tree-view)
  6x -6:29.1.0 core:backspace (input.hidden-input)
     -3:19.2.0 core:save (input.hidden-input)
     -3:18.1.0 core:backspace (input.hidden-input)
  2x -3:17.9.0 core:save (input.hidden-input)
     -1:32.1.0 core:backspace (input.hidden-input)
     -1:31.9.0 core:save (input.hidden-input)
     -1:21.2.0 command-palette:toggle (input.hidden-input)
  2x -1:20.1.0 core:backspace (input.hidden-input)
     -1:17.3.0 core:move-down (input.hidden-input)
     -1:17.1.0 core:confirm (input.hidden-input)
     -1:17.1.0 settings-view:install-packages-and-themes (input.hidden-input)
  4x -1:05.1.0 core:confirm (input.hidden-input)
  3x -1:04.0 core:backspace (input.hidden-input)
     -1:03.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-discord 2.0.2 
language-assembly 0.7.2 
teletype 0.13.4 
```

**Comment by 404-LogicNotFound** [comment]
I am Having the same issue. How to resolve this?

**Comment by sup-Udh** [comment]
Ye same problem fr me too..

**Comment by TadeeshaNithesh** [comment]
I'm also have this problem
https://stackoverflow.com/questions/63504594/error-cannot-find-module-vue-loader-v16-package-json
sometimes this will be help you
