### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by Mik1337** [HelloWorld017/atom-discord#30]
[Enter steps to reproduce:]

1. $ apm install atom-discord
or
2. packages -> atom-discord -> install atom-discord (from atom)

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: "Fedora release
**Thrown From**: [atom-discord](https://github.com/HelloWorld017/atom-discord) package 1.4.0

### Stack Trace

Failed to load the atom-discord package

```
At Unexpected token (

SyntaxError: Unexpected token (
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Non-Core Packages

```
atom-discord 1.4.0 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
deep-space-syntax 1.1.0 
intentions 1.1.5 
jupyter-notebook 0.0.10 
linter 2.2.0 
linter-ui-default 1.2.4 
platformio-ide-terminal 2.7.0 
python-jedi 0.3.8 
```

I tried running ``npm install`` in ``~/.atom/packages/atom-discord``, no dice

**Comment by HelloWorld017** [comment]
It is strange because when I installed 1.4.0, there were no syntax errors.

**Comment by HelloWorld017** [comment]
When I tried it in the Atom 1.13.1, same error have occured. It is error of async/await and should be babel-ed or change minimum atom version.

**Comment by Mik1337** [comment]
Upgrading Atom to the latest version [1.22.1](https://github.com/atom/atom/releases/tag/v1.22.1) fixes this issue, so I'm closing this. Thanks for the support
