### ISSUE TITLE
Failed to activate the atom-discord package

### ISSUE THREAD

**Issue by UNCH4RTED** [HelloWorld017/atom-discord#56]
**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Windows 10 x64 Home
**Thrown From**: [atom-discord](https://github.com/HelloWorld017/atom-discord) package 1.6.0

### Stack Trace

Failed to activate the atom-discord package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.27.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-discord/src/index.js:6:13)
    at /packages/atom-discord/src/index.js:498:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.27.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.27.2/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:220:40)
    at measure (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.27.2/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.27.2/resources/app/src/atom-environment.js:871:27)
```

### Commands

```
```

### Non-Core Packages

```
atom-discord 1.6.0 
```

**Comment by HelloWorld017** [comment]
For now, please try installing from source code.
I'll download atom 1.27.2 and test.

**Comment by UNCH4RTED** [comment]
Thx, that worked

**Comment by HelloWorld017** [comment]
I downloaded atom 1.29.0-beta and installed from atom registry but I couldn't find the issue.

**Comment by AnotaOCaio** [comment]
I'm having the same error, even trying to download from Source Code. Can you help me?
