### ISSUE TITLE
Cannot find module 'vue'

### ISSUE THREAD

**Issue by devakira** [HelloWorld017/atom-discord#59]
## Steps to reproduce
1.   Update atom-discord to 1.6.1
2. Restart atom

## Stacktrace
```
Error: Cannot find module 'vue'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-discord/src/index.js:6:13)
    at /packages/atom-discord/src/index.js:503:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.27.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.27.2/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:220:40)
    at measure (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.27.2/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.27.2/resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

## Information
**Platform**: Microsoft Windows 10 Home 10.0.17134 Build 17134
**Atom**: 1.27.2
**Package Version**: v1.6.1

### Non-Core Packages
```
atom-discord 1.6.1 
atom-html-preview 0.2.5 
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
pigments 0.40.2 
wakatime 7.0.4 
```

**Comment by HelloWorld017** [comment]
Did you installed via source?

**Comment by devakira** [comment]
No, I installed it through apm

**Comment by HelloWorld017** [comment]
First, please reinstall atom-discord.
If that doesn't work, please upload folders in `~/.atom/packages/atom-discord/node_modules/` via pastbin.

(If that is hard, please say count of folders in node_modules and existence of node_modules/vue)

If there is no node_modules, please say that there is no node_modules folder.
