### ISSUE TITLE
Cannot find module 'vue'

### ISSUE THREAD

**Issue by crocrodail** [HelloWorld017/atom-discord#67]
When I run atom I have this message "At Cannot find module 'vue'"
I installed the source code.

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Windows 10
**Thrown From**: [atom-discord](https://github.com/HelloWorld017/atom-discord) package 1.6.1

### Stack Trace

Failed to activate the atom-discord package

```
At Cannot find module 'vue'

Error: Cannot find module 'vue'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.31.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.31.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.31.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-discord/src/index.js:6:13)
    at /packages/atom-discord/src/index.js:508:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.31.1/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:220:40)
    at measure (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.31.1/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.31.1/resources/app/src/package-manager.js:696:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.31.1/resources/app/src/package-manager.js:671:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.31.1/resources/app/src/config.js:852:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.31.1/resources/app/src/package-manager.js:669:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.31.1/resources/app/src/package-manager.js:648:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.31.1/resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

### Non-Core Packages

```
atom-discord 1.6.1 
atom-material-syntax 1.0.8 
busy-signal 1.4.3 
floobits 0.32.12 
goto-edited-position 0.3.0 
highlight-selected 0.14.0 
intentions 1.1.5 
language-lua 0.9.11 
language-todotxt 1.1.5 
linter 2.2.0 
linter-json-lint 0.1.3 
linter-lua 1.0.4 
linter-luaparse 0.2.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
olivia-syntax 0.2.0 
```

**Comment by HelloWorld017** [comment]
You should execute `$ npm install` in the atom-discord root.

**Comment by HelloWorld017** [comment]
Duplicated with #59
