### ISSUE TITLE
I can't launch atom-discord

### ISSUE THREAD

**Issue by Prosta4okua** [HelloWorld017/atom-discord#85]
**Please use this template only if issue related to Error / Unexpected behavior**  
**Please use suitable tags**

## Step to reproduce
1.   I just downloaded atom-discord and restarted this.
2.   
3.   
4.   

## Stacktrace
```
  Fill this section if this issue is for error-thrown bug.
  If not, please delete this section.
  
  Error: 
  Error: Cannot find module 'vue'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:154765)
    at Module.require (file:///C:/Users/danya/AppData/Local/atom/app-1.36.0/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:146072)
    at Object.<anonymous> (C:\Users\danya\.atom\packages\atom-discord\src\index.js:7:13)
    at Object.<anonymous> (C:\Users\danya\.atom\packages\atom-discord\src\index.js:336:3)
    at Module.get_Module._compile (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:146782)
    at Object.value [as .js] (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/danya/AppData/Local/atom/app-1.36.0/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:1:674943)
    at Package.requireMainModule (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:3186680)
    at measure (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:3173391)
    at Package.measure (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:3172223)
    at Package.load (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:3172964)
    at PackageManager.loadAvailablePackage (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:381389)
    at config.transact (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:379812)
    at Config.transact (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:332345)
    at PackageManager.loadPackages (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:379750)
    at t.loadState.then (C:\Users\danya\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:1:695089)
    at <anonymous>
```

## Information
**Platform**: Windows x64
**Atom**: 1.36.0
**Package Version**: idk what is it

### Non-Core Packages
```
blah-blah 0.3.1
```

**Comment by HelloWorld017** [comment]
Please run `$ npm install` & refer to #59
