### ISSUE TITLE
Built for older version of Atom

### ISSUE THREAD

**Issue by samcarsonx** [HelloWorld017/atom-discord#88]
## Step to reproduce
1.   Start Atom on the latest version (1.41.0) with atom-discord 2.0.2

## Bug
`Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.`

## Stacktrace
This is what was printed when I attempted to rebuild it for the correct version of Atom. I don't have Xcode.
```
ode-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.0/fse-v1.2.0-electron-v4.2-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.0 and electron@4.2.7 (electron-v4.2 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/samcarson/.atom/packages/atom-discord/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/samcarson/.atom/packages/atom-discord/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64" "--napi_version=3" "--node_abi_napi=napi" "--python=/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"
gyp ERR! cwd /Users/samcarson/.atom/packages/atom-discord/node_modules/fsevents
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/samcarson/.atom/packages/atom-discord/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64/fse.node --module_name=fse --module_path=/Users/samcarson/.atom/packages/atom-discord/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64 --napi_version=3 --node_abi_napi=napi --python=/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/samcarson/.atom/packages/atom-discord/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 19.0.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/samcarson/.atom/packages/atom-discord/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/samcarson/.atom/packages/atom-discord/node_modules/fsevents
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@1.2.0 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Information
**Platform**: macOS 10.15 Catalina
**Atom**: 1.41.0
**Package Version**: 2.0.2

**Comment by HelloWorld017** [comment]
Actually, I couldn't find native modules in dependencies.
But in development dependencies, which are useless except you are developing atom-discord, there was a native module named `fsevents` (You can see it in your log).
Unfortunately, it is installed only in Mac OS, so I couldn't test for it.

So I have updated some dependencies in latest commit, but it could not be fixed.

For workaround, if you installed with git, please try delete node_modules folder and `git pull` and `npm i --only=prod`. It will only install production dependencies, not development dependencies.
