### ISSUE TITLE
Atom Discord won't work anymore

### ISSUE THREAD

**Issue by Sinnoma** [HelloWorld017/atom-discord#90]
**Please use this template only if issue related to Error / Unexpected behavior**  
**Please use suitable tags**

## Step to reproduce
1. Install Atom Discord

## Information
**Platform**: macOS Sierra : 10.12.6
**Atom**: 1.43.0
**Package Version**: 2.0.2, installed with source code

I don't really know what's happening, ngl
Firstly, it worked as intended, and one day, I've set the update tick to 1, and then I suppose that Discord rate limited me.
Then I wasn't able anymore to set a custom activity.

I've took a look to the console and there's a spam in.

Take a look to the following link, this is the image of the "spam" : https://anonymousfiles.io/ogkgWfAy/ (Sorry for the not really trustable link).

**Comment by HelloWorld017** [comment]
Could you upload your atom-discord log here?

1. Enable logging in atom-discord Settings > Troubleshootings.
2. Reboot atom
3. You can get your log at ~/.atom/atom-discord/log.txt

**Comment by Sinnoma** [comment]
The file is empty.

**Comment by Sinnoma** [comment]
Ok so the file has been filled up after some time and here's what I've got :

```
[18:19:39 GMT+0100 (heure normale d’Europe centrale)] Initializing configs...
[18:19:39 GMT+0100 (heure normale d’Europe centrale)] [Configs]
{ behaviour:
   { customAppId: '669223041322057769',
     defaultProjectName: 'a project',
     updateTick: 15000 },
  detail: { text: 'working-project', textCustom: '' },
  elapsed: { handleRest: 'false', handleRestDelay: 60, send: true },
  i18n: 'en-US',
  largeImage:
   { image: 'currentType',
     imageCustom: '',
     text: 'type-description',
     textCustom: '' },
  rest:
   { detail: 'working-project',
     detailCustom: '',
     fileName: 'editing-idle',
     fileNameCustom: '',
     largeImage: 'rest',
     largeImageCustom: '',
     restOnAfk: false,
     restOnAfkThreshold: 180,
     restOnBlur: false,
     restOnBlurThreshold: 0,
     smallImage: 'default',
     smallImageCustom: '',
     smallImageText: 'atom-description',
     smallImageTextCustom: '',
     typeName: 'developer-idle',
     typeNameCustom: '' },
  smallImage:
   { image: 'atom',
     imageCustom: '',
     text: 'atom-description',
     textCustom: '' },
  state: { text: 'editing-file', textCustom: '' },
  troubleShooting:
   { debugLog: true,
     noDiscordNotification: true,
     ubuntuPatch: false } }
[18:19:39 GMT+0100 (heure normale d’Europe centrale)] Initializing RPC...
[18:19:39 GMT+0100 (heure normale d’Europe centrale)] Logging in RPC with ID 669223041322057769
[18:19:40 GMT+0100 (heure normale d’Europe centrale)] Logged in successfully.
[18:19:40 GMT+0100 (heure normale d’Europe centrale)] Editor llfzz2kha4o became online.
[18:19:40 GMT+0100 (heure normale d’Europe centrale)] New editor confirmed, sending activities...
[18:19:40 GMT+0100 (heure normale d’Europe centrale)] Error while sending Activity : { Error
    at t.value (/Users/mauroypolette/.Trash/atom-discord/atom-discord/dist/rpc.bundle.js:1:97169)
    at t.emit (events.js:182:13)
    at /Users/mauroypolette/.Trash/atom-discord/atom-discord/dist/rpc.bundle.js:1:70970
    at L (/Users/mauroypolette/.Trash/atom-discord/atom-discord/dist/rpc.bundle.js:1:70111)
    at Socket.<anonymous> (/Users/mauroypolette/.Trash/atom-discord/atom-discord/dist/rpc.bundle.js:1:70788)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
 code: 1000, data: { code: 1000, message: '' } }
[18:19:40 GMT+0100 (heure normale d’Europe centrale)] Activity: { state: 'Idle',
  details: 'Working on a project',
  largeImageKey: 'rest',
  largeImageText: 'The Developer is RESTful enough to rest!',
  smallImageKey: 'atom',
  smallImageText: 'Working with Atom',
  startTimestamp: 1580491179 }
[18:19:55 GMT+0100 (heure normale d’Europe centrale)] Error while sending Activity : { Error
    at t.value (/Users/mauroypolette/.Trash/atom-discord/atom-discord/dist/rpc.bundle.js:1:97169)
    at t.emit (events.js:182:13)
    at /Users/mauroypolette/.Trash/atom-discord/atom-discord/dist/rpc.bundle.js:1:70970
    at L (/Users/mauroypolette/.Trash/atom-discord/atom-discord/dist/rpc.bundle.js:1:70111)
    at Socket.<anonymous> (/Users/mauroypolette/.Trash/atom-discord/atom-discord/dist/rpc.bundle.js:1:70788)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
 code: 1000, data: { code: 1000, message: '' } }
[18:19:55 GMT+0100 (heure normale d’Europe centrale)] Activity: { state: 'Idle',
  details: 'Working on a project',
  largeImageKey: 'rest',
  largeImageText: 'The Developer is RESTful enough to rest!',
  smallImageKey: 'atom',
  smallImageText: 'Working with Atom',
  startTimestamp: 1580491179 }
```

**Comment by HelloWorld017** [comment]
According to the discord, the error 1000 seems to mean `Unknown Error` (not really helpful).

First, does the symptom persist when you use the default app id?

Second, if it persists, I recommend you to reinstall discord.

**Comment by Sinnoma** [comment]
**Issue found**, this is happening when 2/3 Discord instance is installed on the computer.

That doesn't need to launch 2 Discord at the same time, but simply having it installed will make in trouble Atom Discord.
