### ISSUE TITLE
Failed to load the atom-discord package

### ISSUE THREAD

**Issue by Rayn322** [HelloWorld017/atom-discord#91]
[Enter steps to reproduce:]

1. Install atom-discord via the package manager
2. Run

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [atom-discord](https://github.com/HelloWorld017/atom-discord) package 2.0.2

### Stack Trace

Failed to load the atom-discord package

```
At Cannot find module 'vue'

Error: Cannot find module 'vue'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-discord/src/index.js:7:13)
    at /packages/atom-discord/src/index.js:336:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:694511)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3226484)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3213024)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3211856)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3212597)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381026)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379754)
    at PackageManager.disablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:375358)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2660945)
```

### Commands

```
```

### Non-Core Packages

```
atom-discord 2.0.2 
atom-monokai 0.10.9 
autocomplete-python 1.16.0 
darkpython-syntax 0.5.0 
es6-javascript 1.0.0 
file-icons 2.1.39 
platformio-ide-terminal 2.10.0 
turbo-javascript 1.4.0 
```

**Comment by Rayn322** [comment]
I reinstalled and it worked.

**Comment by MineEnd** [comment]
windows too load failed
