### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sendLargeImage' of undefined

### ISSUE THREAD

**Issue by s8tattooSystems** [HelloWorld017/atom-discord#93]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [atom-discord](https://github.com/HelloWorld017/atom-discord) package 2.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'sendLargeImage' of undefined

```
At /private/tmp/atom-discord/src/config.js:588

TypeError: Cannot read property 'sendLargeImage' of undefined
    at Function.module.exports.migrateV1toV2 (/private/tmp/atom-discord/src/config.js:588:13)
    at HTMLElement.atom.commands.add (/private/tmp/atom-discord/src/index.js:338:18)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349290)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:699460)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:875983)
    at SelectListView.didClickItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:873925)
    at ListItemView.onclick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:872915)
    at ListItemView.didClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:877003)
```

### Commands

```
     -7:29.8.0 command-palette:toggle (input.hidden-input)
  5x -7:28.9.0 core:backspace (input.hidden-input)
     -7:21.3.0 atom-discord:migrate (input.hidden-input)
     -7:06.1.0 command-palette:toggle (input.hidden-input)
  2x -7:03.3.0 core:move-down (input.hidden-input)
     -7:02.3.0 core:confirm (input.hidden-input)
     -7:02.3.0 atom-discord:toggle (input.hidden-input)
     -6:51.2.0 command-palette:toggle (input.hidden-input)
  2x -6:45 core:move-down (input.hidden-input)
     -6:43.9.0 core:confirm (input.hidden-input)
     -6:43.9.0 atom-discord:project-customize (input.hidden-input)
     -0:24.4.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16.3.0 core:confirm (input.hidden-input)
     -0:16.3.0 atom-discord:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:13.9.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.8.0 atom-discord:migrate (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-discord 2.0.2 
atom-material-syntax 1.0.8 
autocomplete-python 1.16.0 
Hydrogen 2.14.1 
kite 0.178.0 
python-autopep8 0.1.3 
script 3.25.0 
structure-view 0.2.1 
```

**Comment by nonoesimposible** [comment]
same issue with 2.0.2 on Arch (exception occurs when calling `Atom Discord: Migrate`)
