### ISSUE TITLE
2.0.2 Build failed on Atom 1.47.0, macOS Catalina

### ISSUE THREAD

**Issue by allexks** [HelloWorld017/atom-discord#97]
## Step to reproduce
1.   Open Atom

## Stacktrace
```
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
Rebuild Failed
atom-discord 2.0.2
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.0/fse-v1.2.0-electron-v5.0-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.0 and electron@5.0.13 (electron-v5.0 ABI, unknown) (falling back to source compile with node-gyp) 
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:204:1: note: expanded from here
ToBoolean
^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:2387:3: note: 'ToBoolean' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("ToBoolean can never throw. Use Local version.",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
X(bool, Boolean)
^
../../nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:211:1: note: expanded from here
BooleanValue
^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:2432:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:103:37: warning: 'New' is deprecated: Use maybe version [-Wdeprecated-declarations]
  return scope.Escape(v8::Function::New( isolate
                                    ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:4026:10: note: 'New' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:28: warning: 'New' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:5313:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1034:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:2418:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1044:27: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:2627:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1818:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                           ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1824:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(key, value);
                           ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1830:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(index, value);
                           ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3268:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1836:32: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
                               ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3313:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1842:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(key));
                                               ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3313:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1847:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(index));
                                               ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3317:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:24:25: warning: 'IsNearDeath' is deprecated: Garbage collection internal state should not be relied on. [-Wdeprecated-declarations]
    assert(persistent().IsNearDeath());
                        ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:571:3: note: 'IsNearDeath' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:67:18: warning: 'MarkIndependent' is deprecated: Objects are always considered independent. Use MarkActive to avoid collecting otherwise dead weak handles. [-Wdeprecated-declarations]
    persistent().MarkIndependent();
                 ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:553:3: note: 'MarkIndependent' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:124:26: warning: 'IsNearDeath' is deprecated: Garbage collection internal state should not be relied on. [-Wdeprecated-declarations]
    assert(wrap->handle_.IsNearDeath());
                         ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:571:3: note: 'IsNearDeath' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:51:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> exports);
                           ~~~~^
In file included from ../fsevents.cc:86:
../src/constants.cc:89:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagNone").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagNone));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:90:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMustScanSubDirs").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagMustScanSubDirs));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:91:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUserDropped").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagUserDropped));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:92:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagKernelDropped").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagKernelDropped));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:93:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagEventIdsWrapped").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagEventIdsWrapped));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:94:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagHistoryDone").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagHistoryDone));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:95:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagRootChanged").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagRootChanged));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:96:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMount").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagMount));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:97:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUnmount").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagUnmount));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:98:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemCreated").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemCreated));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:99:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRemoved").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemRemoved));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:100:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemInodeMetaMod").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemInodeMetaMod));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:101:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRenamed").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemRenamed));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:102:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemModified").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemModified));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:103:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemFinderInfoMod").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemFinderInfoMod));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:104:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemChangeOwner").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemChangeOwner));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:105:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemXattrMod").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemXattrMod));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:106:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsFile").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemIsFile));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:107:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsDir").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemIsDir));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:86:
../src/constants.cc:108:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsSymlink").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemIsSymlink));
          ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/yalishanda/.atom/.node-gyp/.node-gyp/5.0.13/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:89:16: error: variable has incomplete type 'void'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
               ^
../fsevents.cc:89:31: error: no member named 'Handle' in namespace 'v8'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                          ~~~~^
../fsevents.cc:89:48: error: expected '(' for function-style cast or type construction
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                     ~~~~~~~~~~^
../fsevents.cc:89:50: error: use of undeclared identifier 'exports'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                                 ^
../fsevents.cc:89:58: error: expected ';' after top level declarator
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                                         ^
                                                         ;
35 warnings and 6 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/yalishanda/.atom/packages/atom-discord/node_modules/fsevents/lib/binding/Release/electron-v5.0-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/yalishanda/.atom/packages/atom-discord/node_modules/fsevents/lib/binding/Release/electron-v5.0-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/yalishanda/.atom/packages/atom-discord/node_modules/fsevents
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/yalishanda/.atom/packages/atom-discord/node_modules/fsevents/lib/binding/Release/electron-v5.0-darwin-x64/fse.node --module_name=fse --module_path=/Users/yalishanda/.atom/packages/atom-discord/node_modules/fsevents/lib/binding/Release/electron-v5.0-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/yalishanda/.atom/packages/atom-discord/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 19.4.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/yalishanda/.atom/packages/atom-discord/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/yalishanda/.atom/packages/atom-discord/node_modules/fsevents
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@1.2.0 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yalishanda/.atom/.apm/_logs/2020-05-22T16_51_01_306Z-debug.log
```

## Information
**Platform**: macOS 10.15.4  
**Atom**: 1.47.0  
**Package Version**: 2.0.2

Didn't happen until 2 or 3 days ago. Haven't installed other Atom packages in a while.

**Comment by biagios** [comment]
I got the same issue, what worked for me was going to the directory where the package is deleted node_modules and run npm I inside the directory for the package again.

**Comment by biagios** [comment]
> I got the same issue, what worked for me was going to the directory where the package is deleted node_modules and run npm I inside the directory for the package again.

If you need more info just let me know and I can give you a detailed list of what I did.

**Comment by VeryGoodDog** [comment]
> I got the same issue, what worked for me was going to the directory where the package is deleted node_modules and run `npm i` inside the directory for the package again.
> Once you have done this run `npm audit fix`

I got this same issue. I tried your fix but I'm still getting the error.

**Comment by biagios** [comment]
> > I got the same issue, what worked for me was going to the directory where the package is deleted node_modules and run `npm i` inside the directory for the package again.
> > Once you have done this run `npm audit fix`
> 
> I got this same issue. I tried your fix but I'm still getting the error.

Did you try rebuilding the package once you did all of this?

**Comment by VeryGoodDog** [comment]
> > > I got the same issue, what worked for me was going to the directory where the package is deleted node_modules and run `npm i` inside the directory for the package again.
> > > Once you have done this run `npm audit fix`
> > 
> > 
> > I got this same issue. I tried your fix but I'm still getting the error.
> 
> Did you try rebuilding the package once you did all of this?

I did now, and it works. Thanks.

**Comment by biagios** [comment]
@allexks Just wondering in order for this issue to be marked as closed, has the issue been fixed?

**Comment by allexks** [comment]
> @allexks Just wondering in order for this issue to be marked as closed, has the issue been fixed?

I perfomed the workaround that you suggested and it fixed the problem. Does this count?
